development:
  adapter: postgresql
  database: rrivas_blog
  username: rrivas_blog
  password: rrivas_blog_password

test:
  adapter: postgresql
  database: rrivas_blog_test
  username: rrivas_blog
  password: rrivas_blog_password
